version: '3.8'

services:
  web:
    build: ./car_dealership
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./car_dealership/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./car_dealership/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=main_db

volumes:
  postgres_data: