# Generated by Django 4.0.2 on 2022-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='car_prices',
            field=models.ManyToManyField(blank=True, null=True, related_name='car_prices', to='car.CarPrices', verbose_name='car_prices'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='cars_config',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars_config', to='car.CarConfiguration', verbose_name='cars_config'),
        ),
    ]
