# Generated by Django 4.0.2 on 2022-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('car', '0001_initial'),
        ('dealer', '0002_alter_dealer_car_prices_alter_dealer_cars_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='car.Car', verbose_name='cars'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='customer.Customer', verbose_name='customer'),
        ),
    ]
