# Generated by Django 4.0.2 on 2022-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('change_date', models.DateField(auto_now=True, verbose_name='change_date')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('found_year', models.DateField(verbose_name='found_name')),
                ('car_prices', models.ManyToManyField(to='car.CarPrices', verbose_name='car_prices')),
                ('cars', models.ManyToManyField(to='car.Car', verbose_name='cars')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
