# Generated by Django 4.0.2 on 2022-02-12 07:16

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('provider', '0001_initial'),
        ('dealer', '0003_alter_dealer_cars_alter_dealer_users'),
        ('customer', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='OfferCar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfferCustomer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfferDealer', to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='MaxOfferPrice'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfferProvider', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sell_date',
            field=models.DateField(auto_now_add=True, verbose_name='OfferSellDate'),
        ),
    ]
