# Generated by Django 4.0.2 on 2022-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_offer_car_alter_offer_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(verbose_name='DiscountPercent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='time_end',
            field=models.DateField(auto_now_add=True, verbose_name='DiscountTimeEnd'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='time_start',
            field=models.DateField(auto_now_add=True, verbose_name='DiscountStartTime'),
        ),
    ]
